### PR TITLE
Added pin mapping for 3.3v logic (Smoothie). Also some display updates.

### PR DESCRIPTION
**Pull request by pristinesource**
Added a pin mapping and a simple #define to turn the D3, TX and RX pins into STEP, DIR and ERROR/ENABLE inputs to bypass the built in level shifter.

The level shifter pins will work with 3.3V as well

### CODE REVIEW

**Comment by pristinesource** [comment]
I see I put the wrong pin numbers for TX and RX, they should be 30 and 31 not 21 and 21.  I am going to do another commit to fix it.

**Comment by pristinesource** [comment]
I also added some updates to the display code
img_3125

**Comment by pristinesource** [comment]
I updated some of the display text:
img_3126
img_3127

**Comment by pristinesource** [comment]
Hmm, I am going to take out "PCB" from the splash screen.

**Comment by Misfittech** [comment]
I love the LCD changes, I have changed the LCD menu system in FW0.07 to be more modular. 

Also the level shift pins will work with 3.3V so there is no reason to use the other pins.

**Comment by pristinesource** [comment]
I did not know they would work for 3.3v, that is awesome!!  Made my job easier ;)  Thank you!!!!!!!!!

**Comment by Misfittech** [comment]
Yes they will even work with 3.3V if the Vin pin is floating.  If Vin has
5V power and you use a Smoothie than the step, dir and error will have a
10K pull up to 5V however the LPC on the smoothie is 5V tolerant so it is
not an issue.


Trampas

**Pull request closed without merging**
